def print_view():
  print("Welcome to My world of maths")
  print("Please select the choice you want to perform: ")
  print("999. Exit")
  print("2007. Read DataBase:")
  print("1 for addition")
  print("2 for subtraction")
  print("3 for multiplication")
  print("4 for division")
  print("5 for power")
  print("6 for square root")
  print("7 for cube root")
  print("8 for factorial")
  print("9 for n choose r")
  print("10 for greatest common divisor")
  print("11 for table")
  print("12 for square table")
  print("13 for cude table")
  print("14 for units")

def meger():
  print("Welcome to the Unit Converter!")
  print("1. Kilograms to Pounds")
  print("2. Pounds to Kilograms")
  print("3. Meters to Feet")
  print("4. Feet to Meters")
  print("5. Liters to Gallons")
  print("6. Gallons to Liters")
  print("7. Miles to Kilometers")
  print("8. Kilometers to Miles")
  print("9. Inches to Centimeters")
  print("10. Centimeters to Inches")
  print("11. Yards to Meters")
  print("12. Meters to Yards")
  print("13. Millimeters to Inches")
  print("14. Inches to Millimeters")
  print("15. Millimeters to Feet")
  print("16. Feet to Millimeters")
  print("17. Millimeters to Yards")
  print("18. Yards to Millimeters")
  print("19. Millimeters to Miles")
  print("20. Miles to Millimeters")
