def print_view():
  print("Welcome to the Unit Converter!")
  print("Please select the conversion you want to perform:")
  print("999. Exit")
  print("1. Kilograms to Pounds")
  print("2. Pounds to Kilograms")
  print("3. Meters to Feet")
  print("4. Feet to Meters")
  print("5. Liters to Gallons")
  print("6. Gallons to Liters")
  print("7. Miles to Kilometers")
  print("8. Kilometers to Miles")
  print("9. Inches to Centimeters")
  print("10. Centimeters to Inches")
  print("11. Yards to Meters")
  print("12. Meters to Yards")
  print("13. Millimeters to Inches")
  print("14. Inches to Millimeters")
  print("15. Millimeters to Feet")
  print("16. Feet to Millimeters")
  print("17. Millimeters to Yards")
  print("18. Yards to Millimeters")
  print("19. Millimeters to Miles")
  print("20. Miles to Millimeters")
  print("21 for addition")
  print("22 for subtraction")
  print("23 for multiplication")
  print("24 for division")
  print("25 for power")
  print("26 for square root")
  print("27 for cube root")
  print("28 for factorial")
  print("29 for n choose r")
  print("30 for greatest common divisor")
  print("31 for table")
  print("32 for square table")
  print("33 for cude table")
  
  